server:
  port: 8084
google-sheets:
  spreadsheet-id: "1Y2Ua2vLn_mQ-mKhP7CPpX_qzk6In7jIaLL82TbV7zyU" #Artem
  #spreadsheet-id: "1Bkf6G03Gve2yIbfRY1PVHwjFdE1nPGa1-zMa017f1as" #Evgeniy
api-key:
  keitaro: "14850ffae6bbb60067306d2351623db7"
