server:
  port: 8083
google-sheets:
  spreadsheet-id: "1zwGH7RAwTrbAGFMUBqVbHo6Og1FGIoIuseEGlRGyd6U" #Artem
  #spreadsheet-id: "1YfhjaEBFY_phtZ73KsfyLI7np4k_KHalLpi1GQZTZOo" #Evgeniy
api-key:
  keitaro: "9f98b94b68e63800d5eaa8d7a59328e6"
